#!/usr/bin/env node
/**
 * One-command local demo:   npm run demo --prefix app
 * Starts Anvil (if needed), deploys the demo contracts with 90 days of price history, writes app/.env.local,
 * starts the relayer (keeper + simulated market + gas sponsor) and the app. Ctrl+C stops everything.
 * Uses Anvil's public, disposable dev keys. Never point this at a real network.
 */
import { spawn, spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const appDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const rootDir = path.dirname(appDir);
const RPC = process.env.RPC_URL || 'http://127.0.0.1:8545';
const CHAIN_ID = 46630;
const KEYS = { // Anvil dev accounts #0, #2, #3 (public test keys)
  deployer: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80',
  prices: '0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a',
  drip: '0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6',
};
const RELAYER_PORT = process.env.RELAYER_PORT || '8788';
const children = [];
let stopping = false;
const stopAll = () => { if (stopping) return; stopping = true; for (const c of children) { try { c.kill('SIGTERM'); } catch {} } };
for (const sig of ['SIGINT', 'SIGTERM', 'SIGHUP']) process.on(sig, () => { stopAll(); process.exit(0); });
process.on('exit', stopAll);

async function rpc(method, params = []) {
  const res = await fetch(RPC, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method, params }) });
  return (await res.json()).result;
}
const chainUp = async () => { try { return Number(await rpc('eth_chainId')) === CHAIN_ID; } catch { return false; } };
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const need = (bin) => { if (spawnSync('which', [bin]).status !== 0) { console.error(`\n"${bin}" is not installed. Install Foundry: https://getfoundry.sh\n`); process.exit(1); } };

need('forge');
if (!(await chainUp())) {
  need('anvil');
  console.log('▸ Starting a local chain (chain id 46630)…');
  children.push(spawn('anvil', ['--chain-id', String(CHAIN_ID), '--block-time', '1', '--silent'], { stdio: 'ignore' }));
  for (let i = 0; i < 40 && !(await chainUp()); i++) await sleep(250);
  if (!(await chainUp())) { console.error('Anvil did not start.'); process.exit(1); }
} else {
  console.log('▸ Resetting the chain already running at', RPC);
  await rpc('anvil_reset');
}

console.log('▸ Deploying contracts and 90 days of price history (about a minute)…');
const out = spawnSync('forge', ['script', 'contracts/script/DeployDemo.s.sol:DeployDemo', '--rpc-url', RPC, '--broadcast', '--slow'], { cwd: rootDir, env: { ...process.env, DEPLOYER_PRIVATE_KEY: KEYS.deployer }, encoding: 'utf8' });
if (out.status !== 0) { console.error(out.stdout, out.stderr); process.exit(1); }
const broker = out.stdout.match(/DEMO_BROKER: (0x[0-9a-fA-F]{40})/)?.[1];
if (!broker) { console.error('Could not read the broker address from forge output:\n', out.stdout); process.exit(1); }

const relayerUrl = `http://localhost:${RELAYER_PORT}`;
writeFileSync(path.join(appDir, '.env.local'), [
  '# Generated by npm run demo (local chain). Safe to delete.',
  `VITE_BROKER_ADDRESS=${broker}`, `VITE_RPC_URL=${RPC}`, `VITE_CHAIN_ID=${CHAIN_ID}`, 'VITE_DEMO_MODE=true',
  `VITE_RELAYER_URL=${relayerUrl}`, 'VITE_NGN_PER_USD=1500', '',
].join('\n'));
console.log(`▸ Broker ${broker}. Wrote app/.env.local`);

console.log('▸ Starting the relayer (keeper, simulated market, gas sponsor)…');
children.push(spawn(process.execPath, ['server/relayer.js'], { cwd: appDir, stdio: ['ignore', 'inherit', 'inherit'], env: {
  ...process.env, BROKER_ADDRESS: broker, RPC_URL: RPC, CHAIN_ID: String(CHAIN_ID), PORT: RELAYER_PORT,
  KEEPER_PRIVATE_KEY: KEYS.deployer, KEEPER_INTERVAL_MS: '4000',
  PRICE_PRIVATE_KEY: KEYS.prices, PRICE_SOURCE: 'sim', PRICE_INTERVAL_MS: '8000',
  DRIP_PRIVATE_KEY: KEYS.drip,
} }));

console.log('▸ Starting the app…\n\n  Open the URL below. Create an account with a passkey, or choose "Explore with a demo account".\n');
const vite = spawn(process.execPath, [path.join(appDir, 'node_modules', 'vite', 'bin', 'vite.js'), ...(process.env.PORT ? ['--port', process.env.PORT] : [])], { cwd: appDir, stdio: 'inherit' });
children.push(vite);
vite.on('exit', () => { stopAll(); process.exit(0); });
